SELECT TOP (1)
    sr.ScoopReportId,
    sr.CaseId,
    sr.HeaderClaimant,
    sr.HeaderClientFile,
    sr.HeaderClientName,
    sr.HeaderDeltaFile,
    sr.HeaderServiceDate,
    sr.HeaderDateOfLoss,
    sr.FooterMessage,
    sr.SubjectIdentifiers,
    sr.InjuryInformation,
    sr.AdditionalInternetInformation,
    sr.ActivityIndicators,
    sr.EmploymentSummary,
    sr.CriminalHistory,
    sr.CivilHistory,
    sr.FinancialDistress,
    sr.Recommendations,
    sr.ShowRecommendations,
    sr.Identification,
    sr.Miscellaneous,
    sr.Deleted,
    sr.CreatedByUser,
    sr.CreatedOn,
    sr.ModifiedByUser,
    sr.ModifiedOn,
    sr.Disclaimer,
    sr.ReportSummary,
    sr.SocialMediaSummary,
    sr.OnlineSourcesSummary,
    sr.ContactInformation,
    sr.KeyFindingSummary,
    sr.ShowDisclaimer
FROM dbo.ScoopReport sr
WHERE sr.ScoopReportId > @LastId
ORDER BY sr.ScoopReportId;
